name: Shantal Freedman Creations
favicon: null
layout_spectrum: 0.42411
typography_spectrum: 0.73639
title: Shantal Freedman Creations
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dee2e3'
    - '#148e91'
    - '#3d3131'
    - '#b82231'
    - '#8d7757'
  brandStrength: 0.25
  lightness: 0.8460488405544311
  saturation: 0.4375
  rhythmicContrast: 0.663526994176209
purpose: []
