name: Shantal Freedman Creations
favicon: null
layout_spectrum: 0.7315
typography_spectrum: 0.4093
title: Shantal Freedman Creations
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e1e1e1'
    - '#36903d'
    - '#4cb2cd'
    - '#f7b064'
    - '#a7d256'
  brandStrength: 0.0625
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
